apiVersion: v2
name: kdef-controller
description: Flux controller for rendering and applying kdef files
type: application
version: 0.2.12
appVersion: "0.7.1"
home: https://github.com/gsid-nl/kdef
sources:
  - https://github.com/gsid-nl/kdef
maintainers:
  - name: Guido Smit
    email: guido@gsid.nl
