package generator

import (
	"bytes"
	"fmt"
	"regexp"

	"sigs.k8s.io/yaml"

	"github.com/gsid-nl/kdef/internal/version"
)

// cleanYAML removes empty zero-value fields that K8s types serialize (status: {}, strategy: {}, etc.)
var emptyFieldPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?m)^[ ]*\w+: \{\}\n`),  // field: {}
	regexp.MustCompile(`(?m)^[ ]*\w+:\s*\n\z`),   // trailing "field:" at end of doc
	regexp.MustCompile(`(?m)^status:\s*\n`),       // bare status: line
}

func cleanYAML(data []byte) []byte {
	for _, p := range emptyFieldPatterns {
		data = p.ReplaceAll(data, nil)
	}
	return data
}

// RenderYAML serializes manifests for a single app into a multi-document YAML string.
func RenderYAML(manifests []Manifest) ([]byte, error) {
	var buf bytes.Buffer

	for i, m := range manifests {
		if i > 0 {
			buf.WriteString("---\n")
		}

		data, err := marshalWithRaw(m.Object, m.Raw)
		if err != nil {
			return nil, fmt.Errorf("marshal: %w", err)
		}
		buf.Write(data)
	}

	return buf.Bytes(), nil
}

// RenderAllYAML serializes all app manifests into a single multi-document YAML stream.
func RenderAllYAML(allManifests map[string][]Manifest) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("# Generated by kdef %s\n", version.Version))
	first := true

	// Sort app names for deterministic output
	var names []string
	for name := range allManifests {
		names = append(names, name)
	}

	// Sort
	sortStrings(names)

	for _, name := range names {
		manifests := allManifests[name]
		for _, m := range manifests {
			if !first {
				buf.WriteString("---\n")
			}
			first = false

			data, err := marshalWithRaw(m.Object, m.Raw)
			if err != nil {
				return nil, fmt.Errorf("marshal %s: %w", name, err)
			}
			buf.Write(data)
		}
	}

	return buf.Bytes(), nil
}

// marshalWithRaw marshals an object and deep-merges raw YAML if provided.
func marshalWithRaw(obj interface{}, raw string) ([]byte, error) {
	data, err := yaml.Marshal(obj)
	if err != nil {
		return nil, err
	}

	if raw == "" {
		return cleanYAML(data), nil
	}

	// Parse both the generated YAML and the raw YAML as maps, then deep-merge
	var base map[string]interface{}
	if err := yaml.Unmarshal(data, &base); err != nil {
		return nil, fmt.Errorf("unmarshal generated: %w", err)
	}

	var overlay map[string]interface{}
	if err := yaml.Unmarshal([]byte(raw), &overlay); err != nil {
		return nil, fmt.Errorf("unmarshal raw: %w", err)
	}

	merged := deepMerge(base, overlay)
	result, err := yaml.Marshal(merged)
	if err != nil {
		return nil, fmt.Errorf("marshal merged: %w", err)
	}

	return cleanYAML(result), nil
}

// deepMerge recursively merges overlay into base. Overlay values win.
func deepMerge(base, overlay map[string]interface{}) map[string]interface{} {
	result := make(map[string]interface{})
	for k, v := range base {
		result[k] = v
	}
	for k, v := range overlay {
		if baseMap, ok := result[k].(map[string]interface{}); ok {
			if overlayMap, ok := v.(map[string]interface{}); ok {
				result[k] = deepMerge(baseMap, overlayMap)
				continue
			}
		}
		result[k] = v
	}
	return result
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}
