package generator

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/yaml"

	"github.com/gsid-nl/kdef/internal/version"
)

// kindApplyOrder ranks Kubernetes kinds for apply ordering so that cluster-scoped
// and dependency resources are created before the workloads that reference them.
// Lower numbers apply first. Unknown kinds get a high default rank so they
// apply after all known prerequisites but before the catch-all tail.
var kindApplyOrder = map[string]int{
	"Namespace":          0,
	"CustomResourceDefinition": 1,
	"ServiceAccount":     2,
	"ClusterRole":        3,
	"ClusterRoleBinding": 4,
	"Role":               5,
	"RoleBinding":        6,
	"ConfigMap":          10,
	"Secret":             10,
	"SealedSecret":       10,
	"PersistentVolumeClaim": 11,
	"Service":            20,
	"Deployment":         30,
	"StatefulSet":        30,
	"DaemonSet":          30,
	"CronJob":            30,
	"Job":                30,
	"HorizontalPodAutoscaler": 40,
	"Ingress":            50,
	"Certificate":        50,
}

const kindApplyOrderDefault = 25

func kindRank(kind string) int {
	if r, ok := kindApplyOrder[kind]; ok {
		return r
	}
	return kindApplyOrderDefault
}

// objectKind extracts the Kind of a kdef-generated manifest object. All generated
// objects embed metav1.TypeMeta and therefore implement schema.ObjectKind.
func objectKind(obj interface{}) string {
	if ok, good := obj.(interface {
		GroupVersionKind() schema.GroupVersionKind
	}); good {
		return ok.GroupVersionKind().Kind
	}
	if ok, good := obj.(interface {
		GetObjectKind() schema.ObjectKind
	}); good {
		return ok.GetObjectKind().GroupVersionKind().Kind
	}
	return ""
}

// objectName returns the metadata.name of a manifest object, or "" if unavailable.
// Used as a tiebreaker for stable, deterministic output ordering.
func objectName(obj interface{}) string {
	if o, ok := obj.(interface{ GetName() string }); ok {
		return o.GetName()
	}
	return ""
}

// cleanYAML removes empty zero-value fields and strips the top-level `status`
// block entirely. K8s types marshal status with zero-valued struct fields
// (e.g. DaemonSetStatus.NumberMisscheduled = 0), which server-side apply
// rejects because status is a subresource. Stripping status makes the rendered
// YAML safe for `kubectl apply` / `kdef apply`.
var emptyFieldPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?m)^[ ]*\w+: \{\}\n`), // field: {}
	regexp.MustCompile(`(?m)^[ ]*\w+:\s*\n\z`), // trailing "field:" at end of doc
}

func cleanYAML(data []byte) []byte {
	// First pass: unmarshal → drop status → re-marshal. This handles both the
	// bare "status:" case and any populated status block with zero-value
	// numeric fields that would otherwise leak into an apply call.
	var obj map[string]interface{}
	if err := yaml.Unmarshal(data, &obj); err == nil && obj != nil {
		if _, ok := obj["status"]; ok {
			delete(obj, "status")
			if cleaned, err := yaml.Marshal(obj); err == nil {
				data = cleaned
			}
		}
	}

	// Second pass: regex cleanup for remaining empty-value fields.
	for _, p := range emptyFieldPatterns {
		data = p.ReplaceAll(data, nil)
	}
	return data
}

// RenderYAML serializes manifests for a single app into a multi-document YAML string.
func RenderYAML(manifests []Manifest) ([]byte, error) {
	var buf bytes.Buffer

	for i, m := range manifests {
		if i > 0 {
			buf.WriteString("---\n")
		}

		data, err := marshalWithRaw(m.Object, m.Raw)
		if err != nil {
			return nil, fmt.Errorf("marshal: %w", err)
		}
		buf.Write(data)
	}

	return buf.Bytes(), nil
}

// RenderAllYAML serializes all app manifests into a single multi-document YAML stream.
// Manifests are ordered by Kubernetes Kind so that apply-time prerequisites
// (Namespaces, CRDs, ServiceAccounts, ConfigMaps, Secrets, RBAC) land before
// the workloads that reference them. Within a rank, sort is by (app-key, name)
// for deterministic output.
func RenderAllYAML(allManifests map[string][]Manifest) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("# Generated by kdef %s\n", version.Version))

	type entry struct {
		key  string // originating map key (app/resource name) — used for error context + tiebreak
		rank int
		name string
		m    Manifest
	}

	var entries []entry
	for key, manifests := range allManifests {
		for _, m := range manifests {
			entries = append(entries, entry{
				key:  key,
				rank: kindRank(objectKind(m.Object)),
				name: objectName(m.Object),
				m:    m,
			})
		}
	}

	sort.SliceStable(entries, func(i, j int) bool {
		if entries[i].rank != entries[j].rank {
			return entries[i].rank < entries[j].rank
		}
		if entries[i].key != entries[j].key {
			return entries[i].key < entries[j].key
		}
		return entries[i].name < entries[j].name
	})

	for i, e := range entries {
		if i > 0 {
			buf.WriteString("---\n")
		}
		data, err := marshalWithRaw(e.m.Object, e.m.Raw)
		if err != nil {
			return nil, fmt.Errorf("marshal %s: %w", e.key, err)
		}
		buf.Write(data)
	}

	return buf.Bytes(), nil
}

// marshalWithRaw marshals an object and deep-merges raw YAML if provided.
func marshalWithRaw(obj interface{}, raw string) ([]byte, error) {
	data, err := yaml.Marshal(obj)
	if err != nil {
		return nil, err
	}

	if raw == "" {
		return cleanYAML(data), nil
	}

	// Parse both the generated YAML and the raw YAML as maps, then deep-merge
	var base map[string]interface{}
	if err := yaml.Unmarshal(data, &base); err != nil {
		return nil, fmt.Errorf("unmarshal generated: %w", err)
	}

	var overlay map[string]interface{}
	if err := yaml.Unmarshal([]byte(raw), &overlay); err != nil {
		return nil, fmt.Errorf("unmarshal raw: %w", err)
	}

	merged := deepMerge(base, overlay)
	result, err := yaml.Marshal(merged)
	if err != nil {
		return nil, fmt.Errorf("marshal merged: %w", err)
	}

	return cleanYAML(result), nil
}

// deepMerge recursively merges overlay into base. Overlay values win.
func deepMerge(base, overlay map[string]interface{}) map[string]interface{} {
	result := make(map[string]interface{})
	for k, v := range base {
		result[k] = v
	}
	for k, v := range overlay {
		if baseMap, ok := result[k].(map[string]interface{}); ok {
			if overlayMap, ok := v.(map[string]interface{}); ok {
				result[k] = deepMerge(baseMap, overlayMap)
				continue
			}
		}
		result[k] = v
	}
	return result
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}
